commits.message = "${artifactName} ${nextVersion} (was ${currentVersion})"

pullRequests.grouping = [
  { name = "patches", "title" = "Patch updates", "filter" = [{"version" = "patch"}] }
]

updates.pin  = [
  { groupId = "com.typesafe.netty", artifactId = "netty-reactive-streams", version = "2." },
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.13." }
]
