addSbtPlugin("com.eed3si9n"       % "sbt-assembly"    % "1.2.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "1.1.1")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"      % "5.7.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.3")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"  % "1.5.10")
