addSbtPlugin("com.eed3si9n"       % "sbt-assembly"    % "2.3.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.5.4")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "1.1.4")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"      % "5.10.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.7")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"  % "1.11.0")
