name: Release Drafter

on:
  push:
    branches:
      - 3.0.x

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          name: "Play WS, async HTTP client $RESOLVED_VERSION"
          config-name: release-drafts/increasing-patch-version.yml # located in .github/ in the default branch within this or the .github repo
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
